# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages

os:
  - linux
  - osx

r: release

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - HDF5_VERSION=1.8.20
    - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"

before_install: 
  - chmod +x travis_setup.sh
  - ./travis_setup.sh

addons:
  apt:
    packages:
      - subversion
      - autoconf
      - build-essential
      - libtool
      - libmagick++-dev
      
bioc_packages:
  - GenomeInfoDbData
  - DESeq2
  - MAST
  - S4Vectors
  - SummarizedExperiment
  - SingleCellExperiment

r_github_packages:
  - mojaveazure/loomR

warnings_are_errors: false
